import Button from '@/components/ui/button/Button';
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <div className='flex flex-col justify-center items-center w-full h-full gap-6'>
      <h1>Welcome to home page CRUD Project</h1>
      <Link href='/profile'>
        <Button variant='primary'>Go to Profile</Button>
      </Link>
    </div>
  );
}
